TARGET_ROOT=/tmp/

all: $(TARGET_ROOT)\1a.exe \
     $(TARGET_ROOT)\2a.exe \
     $(TARGET_ROOT)\3a.exe \
     $(TARGET_ROOT)\4a.exe \
     $(TARGET_ROOT)\5a.exe \
     $(TARGET_ROOT)\6a.exe \
     $(TARGET_ROOT)\7a.exe \
     $(TARGET_ROOT)\8a.exe \
     $(TARGET_ROOT)\9a.exe \
     $(TARGET_ROOT)\10b.exe \
     $(TARGET_ROOT)\1b.exe \
     $(TARGET_ROOT)\2b.exe \
     $(TARGET_ROOT)\3b.exe \
     $(TARGET_ROOT)\4b.exe \
     $(TARGET_ROOT)\5b.exe \
     $(TARGET_ROOT)\6b.exe \
     $(TARGET_ROOT)\7b.exe \
     $(TARGET_ROOT)\8b.exe \
     $(TARGET_ROOT)\9b.exe \
     $(TARGET_ROOT)\10a.exe \

$(TARGET_ROOT)/%.exe: %.cc
	$(CC) -o $@ $<
