#!/s/std/bin/perl
# CS 764 : Project CALF
# author: satish@cs.wisc.edu,shenoy@cs.wisc.edu
# date: 1 Dec 2008

$nrexamples = 10;

sub eval1
{
	for($i = 1; $i < $nrexamples; ++$i){
		print SCHEMA "table Table$i 1\ngroup $i\n";
		print QUERY  "select Table$i 1.0 ";
		for($j = 1; $j <= $i; ++$j){
			print SCHEMA "column column$i_$j int 4\n";
			print QUERY  "column$j ";
		}
		print QUERY  "\n";
		print SCHEMA "\n";
	}
}

sub eval2
{
	for($i = 3; $i < $nrexamples; ++$i){
		$nrg = $i > 3 ? 2 : 1;
		print SCHEMA "table Table$i $nrg\ngroup 3\n";
		print SCHEMA "column scol$_ int 4\n" for (1 ... 3);
		print QUERY  "select Table$i 1.0 scol1 scol2 scol3";
		
		if($i > 3){
			print SCHEMA "group " . ($i -3) . "\n";
			for($j = 0; $j < $i - 3; ++$j){
				print SCHEMA "column column$i_$j int 4\n";
			}
		}
		print QUERY  "\n";
		print SCHEMA "\n";
	}
}

sub eval3
{
	for($i = 1; $i < $nrexamples; ++$i){
		$ng = $i == 9 ? 1 : 2;
		print SCHEMA "table Table$i $ng\ngroup $i\n";
		print SCHEMA "column column$_ int 4\n" for (1 ... $i);
		if( $i < 9){
			print SCHEMA "group " . (9 - $i) . "\n";
			print SCHEMA "column column$_ int 4\n" for ($i+1 ... 9);
		}
		print QUERY  "select Table$i 1.0 ";
		
		for($j = 1; $j <= $i; ++$j){
			print QUERY "column$j ";
		}
		print QUERY  "\n";
		print SCHEMA "\n";
	}
}

sub eval4
{
	$sel = 0;
	for($i = 1; $i < 100; ++$i){
		print SCHEMA "table Table$i 2\ngroup 2\n";
		print SCHEMA "column column$_ int 4\n" for (1 ... 2);
		print SCHEMA "group 3\n";
		print SCHEMA "column column$_ int 4\n" for (3 ... 5);
		print QUERY  "select Table$i $sel column1 column2 column3=1";
		print QUERY  "\n";
		print SCHEMA "\n";
		$sel += 0.00005;
	}
}

sub eval5
{
	$sel = 0;
	for($i = 1; $i < 100; ++$i){
		print SCHEMA "table Table$i 2\ngroup 2\n";
		print SCHEMA "column column$_ int 4\n" for (1 ... 2);
		print SCHEMA "group 3\n";
		print SCHEMA "column column$_ int 4\n" for (3 ... 5);
		print QUERY  "update Table$i $sel column1:1 column4:1 column3=1";
		print QUERY  "\n";
		print SCHEMA "\n";
		$sel += 0.00005;
	}
}

$eval = 5;
open SCHEMA, ">example/eval$eval.schema";
open QUERY,  ">example/eval$eval.query";
eval5();
close SCHEMA;
close QUERY;