#ifndef _GRAMGUARD
#define _GRAMGUARD

// **********************************************************************
// NOTE: This file will eventually be generated by the parser generator
// **********************************************************************

#include "scanner.h"
	 
// **********************************************************************
// Define yylval, a global variable whose value must be set by scanner
// actions.  The value can then be used by whoever called the scanner.
// Note: yylval will eventually be declared in the file gram.tab.c,
//       greated by the parser generator.  For now, it must be declared
//       in main.cc.
// **********************************************************************
typedef TokenType YYSTYPE;  // TokenType is defined in scanner.h
extern YYSTYPE yylval;

// **********************************************************************
// TOKENS
// **********************************************************************
#define INTEGER	       1
#define BOOLEAN	       2
#define STRING	       3
#define VOID	       4
#define TRUE	       5
#define FALSE	       6
#define IF	       7
#define ELSE	       8
#define WHILE	       9
#define WRITE	      10
#define RETURN	      11
#define ID	      12
#define INTLITERAL    13
#define STRINGLITERAL 14
#define LCURLY        15
#define RCURLY        16
#define LPAREN	      17
#define RPAREN	      18
#define COMMA	      19
#define ASSIGN        20
#define SEMICOLON     21
#define PLUS	      22
#define MINUS	      23
#define TIMES	      24
#define DIVIDE	      25
#define NOT           26
#define AND           27
#define OR            28
#define EQUALS	      29
#define NOTEQUALS     30
#define LESS	      31
#define GREATER	      32
#define LESSEQ	      33
#define GREATEREQ     34
#define FLOAT         35
#define FLOATLITERAL  36

#endif
